language: php

sudo: true

php:
  - 5.6

services:
  - mysql

env:
  matrix:
    # - SLAYER_FOLDER="slayer-dev" SLAYER_VERSION="dev-dev" PHALCON_FOLDER="phalcon2_1_x"  PHALCON_VERSION="2.1.x"
    - SLAYER_FOLDER="slayer-dev" SLAYER_VERSION="dev-dev" PHALCON_FOLDER="phalcon2_0_x"  PHALCON_VERSION="2.0.x"
    - SLAYER_FOLDER="slayer-dev" SLAYER_VERSION="dev-dev" PHALCON_FOLDER="phalcon2_0_10" PHALCON_VERSION="phalcon-v2.0.10"
    - SLAYER_FOLDER="slayer-dev" SLAYER_VERSION="dev-dev" PHALCON_FOLDER="phalcon2_0_9"  PHALCON_VERSION="phalcon-v2.0.9"
    - SLAYER_FOLDER="slayer-dev" SLAYER_VERSION="dev-dev" PHALCON_FOLDER="phalcon2_0_8"  PHALCON_VERSION="phalcon-v2.0.8"

  global:
    - MAILER_HOST=smtp.mailgun.org
    - MAILER_PORT=587

    # username
    - secure: "lSFtHAqHNGRjzGBAvcgLezbcz/wib5Giq2zZ2fmKST/YIn/bQHCBG4mx6h1F+vqAT5Td1pnRQ12wtLaVznkocdwLuroox1rKZsO//Z87jQrnUtwmJmkECUpb7bh3SEHp/zb26gsUTrYY18LGatwntTsPBrhdabhslX+UXYdz+O6RztklG+E6XtSOu+iWwuXdfdjfSiVH5/ddZ0ae8WP12AiIgZs1+sZpI93cmYXdxXg3zYmTKNHCvwE02q8ptSt7y1WFAwdNDlHY9JZcBbNZIUYuiGQZwmDN8WtxlE2RlmLs/msgOtZh8EHYQf0mXHFx+tIJARsbyJqJdk/QCiEjM5M0ht4uX2kMDuN/6KESSlABQ9fs4ZJDpni++jEFwkt9UYfYsiCUhDIPD/tn2c3wPKhePoxy2c1epNrDTn8ppc8Z2ur39roNgrdKs4L5cP3wsIqYWiEU12j9q7q0mNao0bA8Ji8qo5Z1QSr8hrQUxzyEChISlVbEYpG5GkV7+enp+ImcnGJ8n6YeeMlE7q3xT9UMsGqiAUUo/SSo3iSAGblejMymKqFKBKczpMdfdnTJyFTMz2FeX5Bx0WfdrGqZTC5U8bCF0sS1udluY1WuvoMfvz7XSDZANv9LbTp4oJEyfSxAqJ1cQtczcz1U4bLNAeuRKPSprvfR0Py4fwGYtzU="

    # password
    - secure: "XwY/rY/RNYGUsQZzAlSbsr7xFnfDJ2/hZAICQQGjmBBDuErfvIU1NrINJ09HPa+LACknuzeAAL519yVifyLA2DTOIDL8NmfZozpEvoLK318Zzgp7uRPtkv3bcFgm1FUt6+QOJlcmlouGOksk+jrdf5F5c6aPrwia5Bz2TQM/mqkiaXa/FIi+6mFu0kCd9JwBcSmYq2HRudg/YU0UL55A2jHKUkz9dCSDGRVA0U9pjl3bTseDlDwTKXjNqrJm1ghY/X2uz+U6Oi/LODQq95aWhvryGAF9YdqhinjoF0iX0LDnsjqNiymaMKtOFgLigRGhczENag4Syzg6BYXB8JPN01KVxZ40gXtA5hkOOKDgq/E5HHYkltbum2dBHQExar6lzwgh2mNtA8xqe627tav1LaPxbRann2qQn5dV52p5Wg6FMFOE0IMTS1+mLwUdUvHTYXWZmMSzXaK1EIi+LmzActJtuzwjkOU91I5S0KtTjpZRoe4jUV+BuY6D+JBr4VaD9hhVMpPtvwPPiwHEKpCvfE0l5JpJ14SAvJiQeo1cSGSjCn4SY60/SUiauzTKN6un6B6q41TEcS8coODZyg9lHJvV2IcxxvKoMpETGSrGRp/Tcvq8oALYlOUSN6FAaMcTgPO8K55cW5ber0lSeadXhQC06bQC3npwPxBwYwEr6cY="
    - MAILER_ENCRYPTION=tls

    # sender email
    - secure: "A7zkhwWeJQoouipZ4t99oGlaMuM9lFkKMFHLbeCy76VBii7oypSV8NXlX1INrhVGjDwutZPro4UNtZLa8VgE81JIia30WnmI7vlrPhz+Q50U9Uc5rDJC5YkiL1J8vieB3UM8E597nx+SgfgtBqdeGniQ2rwEpcsy3vB2IlLnAHNuBRSfny7HdXoiO2uRz1uFLcRnAHIrNrMGfqspTufGn3yDX9DW+1A+QMj++tOckpLSh4C9mB/H23cc9oo7OxLxwi00srYTitZlofI4gmt8d6eqUk2PC47BSoIE/FKJSuaXtTFy8ZbXTGk5H8p4qDXkk2nUrdtp61X+qW/Hc5t7eClzWiI5s/lFTXHJdyJ3d/7sHt+/kLBwz/KKDxd2VWwDd2nQjuhlKOQV2iKIyBNVvtyTy5RxOk9yO8BGmaeD+Dj4TjbH2I0M/X6UwhZrGL5XLvfXCpG0PHZMcryJRNMxK9a+Hmzk7FBu8C4jwnUzv7uAzHJHAoFsmxBS8RyDI+gOy3vlg91/X7GQ4ZjMNvgJCL9YO51uJ3hq4+cDRbCWkJH0R7rCfQIOaK9Lss988NvCSx+bixVnZQDHR6Qi2T8ZgrS9b9Z8l4/GGadJMPp6PtqHsUMnLIsDCmuK1jn4TozLMFBYrPpMqJmBuUp8+f5ShhBod58KFnHag0xn1598/aM="

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - ${PHALCON_FOLDER}

install:
  - curl -s https://raw.githubusercontent.com/phalconslayer/framework/${TRAVIS_BRANCH}/build/ci-build.sh | bash

script:
  - curl -s https://raw.githubusercontent.com/phalconslayer/framework/${TRAVIS_BRANCH}/build/ci-script.sh | bash

notifications:
  email:
    recipients:
      - daison12006013@gmail.com
